version: "3"
services:
  database:
    image: mysql:8.0.11
    ports:
      - "3306:3306"
    volumes:
      - ./var/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: ci2
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1234ci2
  webserver:
    image: sirawat21/php
    command: apt-get install pdo-mysql php5-mysql
    command: systemctl restart apache2
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - database
    links:
      - database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8088:80"
    depends_on:
      - database
    links:
      - database
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1234ci2
      PMA_HOST: database